"""Bootstrap the PostgreSQL runtime schema.

Revision ID: 20260416_0001
Revises:
Create Date: 2026-04-16 00:00:00.000000
"""

from __future__ import annotations

from alembic import op


revision = "20260416_0001"
down_revision = None
branch_labels = None
depends_on = None


UPGRADE_STATEMENTS = [
    """CREATE TABLE csv_ingestion_jobs (
	id VARCHAR(32) NOT NULL, 
	source_path VARCHAR(512) NOT NULL, 
	source_fingerprint VARCHAR(160) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	rows_seen INTEGER NOT NULL, 
	rows_inserted INTEGER NOT NULL, 
	rows_filtered INTEGER NOT NULL, 
	coverage_start_ms BIGINT, 
	coverage_end_ms BIGINT, 
	notes_json JSON NOT NULL, 
	error_message TEXT, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);""",
    """CREATE UNIQUE INDEX ix_csv_ingestion_jobs_source_fingerprint ON csv_ingestion_jobs (source_fingerprint);""",
    """CREATE INDEX ix_csv_ingestion_jobs_status ON csv_ingestion_jobs (status);""",
    """CREATE TABLE market_candles (
	id SERIAL NOT NULL, 
	exchange VARCHAR(16) NOT NULL, 
	market_symbol VARCHAR(128) NOT NULL, 
	base_symbol VARCHAR(64) NOT NULL, 
	quote_asset VARCHAR(16) NOT NULL, 
	instrument_type VARCHAR(16) NOT NULL, 
	timeframe VARCHAR(16) NOT NULL, 
	open_time_ms BIGINT NOT NULL, 
	open FLOAT NOT NULL, 
	high FLOAT NOT NULL, 
	low FLOAT NOT NULL, 
	close FLOAT NOT NULL, 
	vol FLOAT NOT NULL, 
	vol_ccy FLOAT, 
	vol_quote FLOAT, 
	confirm BOOLEAN NOT NULL, 
	is_old_contract BOOLEAN NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_market_candle UNIQUE (exchange, market_symbol, timeframe, open_time_ms)
);""",
    """CREATE INDEX ix_market_candle_base_time ON market_candles (base_symbol, timeframe, open_time_ms);""",
    """CREATE INDEX ix_market_candle_symbol_time ON market_candles (market_symbol, timeframe, open_time_ms);""",
    """CREATE INDEX ix_market_candles_base_symbol ON market_candles (base_symbol);""",
    """CREATE INDEX ix_market_candles_exchange ON market_candles (exchange);""",
    """CREATE INDEX ix_market_candles_market_symbol ON market_candles (market_symbol);""",
    """CREATE INDEX ix_market_candles_open_time_ms ON market_candles (open_time_ms);""",
    """CREATE TABLE market_coverage_snapshots (
	id VARCHAR(32) NOT NULL, 
	active_symbol_count INTEGER NOT NULL, 
	fresh_symbol_count INTEGER NOT NULL, 
	tier1_symbol_count INTEGER NOT NULL, 
	tier1_fresh_symbol_count INTEGER NOT NULL, 
	coverage_ratio FLOAT NOT NULL, 
	dispatch_as_of_ms BIGINT, 
	degraded BOOLEAN NOT NULL, 
	blocked_reason VARCHAR(64), 
	universe_version BIGINT, 
	missing_symbol_count INTEGER NOT NULL, 
	missing_symbols_json JSON NOT NULL, 
	notes_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);""",
    """CREATE INDEX ix_market_coverage_snapshot_created ON market_coverage_snapshots (created_at);""",
    """CREATE TABLE market_instruments (
	id VARCHAR(32) NOT NULL, 
	exchange VARCHAR(16) NOT NULL, 
	instrument_id VARCHAR(128) NOT NULL, 
	base_symbol VARCHAR(64) NOT NULL, 
	quote_asset VARCHAR(16) NOT NULL, 
	instrument_type VARCHAR(16) NOT NULL, 
	lifecycle_status VARCHAR(16) NOT NULL, 
	priority_tier VARCHAR(16) NOT NULL, 
	bootstrap_status VARCHAR(16) NOT NULL, 
	last_trade_price FLOAT, 
	volume_24h_usd FLOAT, 
	discovered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_seen_active_at TIMESTAMP WITH TIME ZONE, 
	delisted_at TIMESTAMP WITH TIME ZONE, 
	missed_refresh_count INTEGER NOT NULL, 
	metadata_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_market_instrument UNIQUE (exchange, instrument_id)
);""",
    """CREATE INDEX ix_market_instrument_lifecycle_tier ON market_instruments (lifecycle_status, priority_tier);""",
    """CREATE INDEX ix_market_instruments_base_symbol ON market_instruments (base_symbol);""",
    """CREATE INDEX ix_market_instruments_bootstrap_status ON market_instruments (bootstrap_status);""",
    """CREATE INDEX ix_market_instruments_exchange ON market_instruments (exchange);""",
    """CREATE INDEX ix_market_instruments_instrument_id ON market_instruments (instrument_id);""",
    """CREATE INDEX ix_market_instruments_lifecycle_status ON market_instruments (lifecycle_status);""",
    """CREATE INDEX ix_market_instruments_priority_tier ON market_instruments (priority_tier);""",
    """CREATE TABLE market_sync_attempts (
	id VARCHAR(32) NOT NULL, 
	exchange VARCHAR(16) NOT NULL, 
	base_symbol VARCHAR(64) NOT NULL, 
	timeframe VARCHAR(16) NOT NULL, 
	queue_name VARCHAR(32) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	retryable BOOLEAN NOT NULL, 
	retry_count INTEGER NOT NULL, 
	page_count INTEGER NOT NULL, 
	inserted_rows INTEGER NOT NULL, 
	error_message TEXT, 
	notes_json JSON NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);""",
    """CREATE INDEX ix_market_sync_attempt_symbol_started ON market_sync_attempts (base_symbol, started_at);""",
    """CREATE INDEX ix_market_sync_attempts_base_symbol ON market_sync_attempts (base_symbol);""",
    """CREATE INDEX ix_market_sync_attempts_exchange ON market_sync_attempts (exchange);""",
    """CREATE INDEX ix_market_sync_attempts_queue_name ON market_sync_attempts (queue_name);""",
    """CREATE INDEX ix_market_sync_attempts_status ON market_sync_attempts (status);""",
    """CREATE TABLE market_sync_cursors (
	id VARCHAR(32) NOT NULL, 
	exchange VARCHAR(16) NOT NULL, 
	base_symbol VARCHAR(64) NOT NULL, 
	timeframe VARCHAR(16) NOT NULL, 
	source_kind VARCHAR(32) NOT NULL, 
	last_synced_open_time_ms BIGINT, 
	status VARCHAR(32) NOT NULL, 
	notes_json JSON NOT NULL, 
	last_sync_started_at TIMESTAMP WITH TIME ZONE, 
	last_sync_completed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_market_sync_cursor UNIQUE (exchange, base_symbol, timeframe, source_kind)
);""",
    """CREATE INDEX ix_market_sync_cursors_base_symbol ON market_sync_cursors (base_symbol);""",
    """CREATE INDEX ix_market_sync_cursors_exchange ON market_sync_cursors (exchange);""",
    """CREATE INDEX ix_market_sync_cursors_status ON market_sync_cursors (status);""",
    """CREATE TABLE market_sync_states (
	id VARCHAR(32) NOT NULL, 
	exchange VARCHAR(16) NOT NULL, 
	base_symbol VARCHAR(64) NOT NULL, 
	timeframe VARCHAR(16) NOT NULL, 
	lifecycle_status VARCHAR(16) NOT NULL, 
	priority_tier VARCHAR(16) NOT NULL, 
	last_synced_open_time_ms BIGINT, 
	fresh_coverage_end_ms BIGINT, 
	next_sync_due_at TIMESTAMP WITH TIME ZONE, 
	status VARCHAR(32) NOT NULL, 
	retry_count INTEGER NOT NULL, 
	lease_owner VARCHAR(128), 
	lease_expires_at TIMESTAMP WITH TIME ZONE, 
	last_error TEXT, 
	last_sync_started_at TIMESTAMP WITH TIME ZONE, 
	last_sync_completed_at TIMESTAMP WITH TIME ZONE, 
	notes_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_market_sync_state_symbol UNIQUE (exchange, base_symbol, timeframe)
);""",
    """CREATE INDEX ix_market_sync_state_due ON market_sync_states (lifecycle_status, priority_tier, next_sync_due_at);""",
    """CREATE INDEX ix_market_sync_states_base_symbol ON market_sync_states (base_symbol);""",
    """CREATE INDEX ix_market_sync_states_exchange ON market_sync_states (exchange);""",
    """CREATE INDEX ix_market_sync_states_lifecycle_status ON market_sync_states (lifecycle_status);""",
    """CREATE INDEX ix_market_sync_states_priority_tier ON market_sync_states (priority_tier);""",
    """CREATE INDEX ix_market_sync_states_status ON market_sync_states (status);""",
    """CREATE TABLE skills (
	id VARCHAR(32) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	raw_text TEXT NOT NULL, 
	source_hash VARCHAR(128) NOT NULL, 
	validation_status VARCHAR(32) NOT NULL, 
	review_status VARCHAR(32) NOT NULL, 
	envelope_json JSON NOT NULL, 
	validation_errors_json JSON NOT NULL, 
	validation_warnings_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);""",
    """CREATE INDEX ix_skills_source_hash ON skills (source_hash);""",
    """CREATE TABLE backtest_runs (
	id VARCHAR(32) NOT NULL, 
	skill_id VARCHAR(32) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	scope VARCHAR(32) NOT NULL, 
	start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	initial_capital FLOAT NOT NULL, 
	benchmark_name VARCHAR(128) NOT NULL, 
	total_trigger_count INTEGER NOT NULL, 
	completed_trigger_count INTEGER NOT NULL, 
	control_requested VARCHAR(32), 
	last_processed_trace_index INTEGER, 
	last_processed_trigger_time_ms BIGINT, 
	summary_json JSON, 
	last_runtime_error_json JSON, 
	error_message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(skill_id) REFERENCES skills (id)
);""",
    """CREATE INDEX ix_backtest_runs_skill_id ON backtest_runs (skill_id);""",
    """CREATE INDEX ix_backtest_runs_status ON backtest_runs (status);""",
    """CREATE TABLE execution_strategy_states (
	id VARCHAR(32) NOT NULL, 
	skill_id VARCHAR(32) NOT NULL, 
	scope_kind VARCHAR(32) NOT NULL, 
	scope_id VARCHAR(32) NOT NULL, 
	state_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_execution_strategy_state_scope UNIQUE (scope_kind, scope_id), 
	FOREIGN KEY(skill_id) REFERENCES skills (id)
);""",
    """CREATE INDEX ix_execution_strategy_state_skill_scope ON execution_strategy_states (skill_id, scope_kind, scope_id);""",
    """CREATE INDEX ix_execution_strategy_states_scope_id ON execution_strategy_states (scope_id);""",
    """CREATE INDEX ix_execution_strategy_states_scope_kind ON execution_strategy_states (scope_kind);""",
    """CREATE INDEX ix_execution_strategy_states_skill_id ON execution_strategy_states (skill_id);""",
    """CREATE TABLE live_tasks (
	id VARCHAR(32) NOT NULL, 
	skill_id VARCHAR(32) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	cadence VARCHAR(16) NOT NULL, 
	cadence_seconds INTEGER NOT NULL, 
	last_triggered_at TIMESTAMP WITH TIME ZONE, 
	last_completed_slot_as_of_ms BIGINT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(skill_id) REFERENCES skills (id)
);""",
    """CREATE INDEX ix_live_tasks_skill_id ON live_tasks (skill_id);""",
    """CREATE INDEX ix_live_tasks_status ON live_tasks (status);""",
    """CREATE TABLE portfolio_books (
	id VARCHAR(32) NOT NULL, 
	skill_id VARCHAR(32) NOT NULL, 
	scope_kind VARCHAR(32) NOT NULL, 
	scope_id VARCHAR(32) NOT NULL, 
	initial_capital FLOAT NOT NULL, 
	cash_balance FLOAT NOT NULL, 
	equity FLOAT NOT NULL, 
	realized_pnl FLOAT NOT NULL, 
	unrealized_pnl FLOAT NOT NULL, 
	last_mark_time_ms BIGINT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_portfolio_book_scope UNIQUE (scope_kind, scope_id), 
	FOREIGN KEY(skill_id) REFERENCES skills (id)
);""",
    """CREATE INDEX ix_portfolio_book_skill_scope ON portfolio_books (skill_id, scope_kind, scope_id);""",
    """CREATE INDEX ix_portfolio_books_scope_id ON portfolio_books (scope_id);""",
    """CREATE INDEX ix_portfolio_books_scope_kind ON portfolio_books (scope_kind);""",
    """CREATE INDEX ix_portfolio_books_skill_id ON portfolio_books (skill_id);""",
    """CREATE TABLE strategy_states (
	id VARCHAR(32) NOT NULL, 
	skill_id VARCHAR(32) NOT NULL, 
	state_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(skill_id) REFERENCES skills (id)
);""",
    """CREATE UNIQUE INDEX ix_strategy_states_skill_id ON strategy_states (skill_id);""",
    """CREATE TABLE live_signals (
	id VARCHAR(32) NOT NULL, 
	live_task_id VARCHAR(32) NOT NULL, 
	trigger_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	signal_json JSON NOT NULL, 
	delivery_status VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(live_task_id) REFERENCES live_tasks (id)
);""",
    """CREATE INDEX ix_live_signals_live_task_id ON live_signals (live_task_id);""",
    """CREATE TABLE portfolio_fills (
	id VARCHAR(32) NOT NULL, 
	book_id VARCHAR(32) NOT NULL, 
	market_symbol VARCHAR(128) NOT NULL, 
	action VARCHAR(32) NOT NULL, 
	side VARCHAR(8) NOT NULL, 
	quantity FLOAT NOT NULL, 
	price FLOAT NOT NULL, 
	notional FLOAT NOT NULL, 
	realized_pnl FLOAT NOT NULL, 
	closed_trade_pnl FLOAT, 
	closed_trade_win BOOLEAN, 
	trigger_time_ms BIGINT NOT NULL, 
	trace_index INTEGER, 
	execution_reference VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(book_id) REFERENCES portfolio_books (id)
);""",
    """CREATE INDEX ix_portfolio_fill_book_time ON portfolio_fills (book_id, trigger_time_ms);""",
    """CREATE INDEX ix_portfolio_fills_book_id ON portfolio_fills (book_id);""",
    """CREATE INDEX ix_portfolio_fills_market_symbol ON portfolio_fills (market_symbol);""",
    """CREATE INDEX ix_portfolio_fills_trigger_time_ms ON portfolio_fills (trigger_time_ms);""",
    """CREATE TABLE portfolio_positions (
	id VARCHAR(32) NOT NULL, 
	book_id VARCHAR(32) NOT NULL, 
	market_symbol VARCHAR(128) NOT NULL, 
	direction VARCHAR(8) NOT NULL, 
	quantity FLOAT NOT NULL, 
	avg_entry_price FLOAT NOT NULL, 
	mark_price FLOAT NOT NULL, 
	position_notional FLOAT NOT NULL, 
	unrealized_pnl FLOAT NOT NULL, 
	unrealized_pnl_pct FLOAT NOT NULL, 
	cycle_realized_pnl FLOAT NOT NULL, 
	stop_loss_json JSON, 
	take_profit_json JSON, 
	opened_at_ms BIGINT NOT NULL, 
	updated_at_ms BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_portfolio_position_book_symbol UNIQUE (book_id, market_symbol), 
	FOREIGN KEY(book_id) REFERENCES portfolio_books (id)
);""",
    """CREATE INDEX ix_portfolio_position_book_symbol ON portfolio_positions (book_id, market_symbol);""",
    """CREATE INDEX ix_portfolio_positions_book_id ON portfolio_positions (book_id);""",
    """CREATE INDEX ix_portfolio_positions_market_symbol ON portfolio_positions (market_symbol);""",
    """CREATE TABLE run_traces (
	id VARCHAR(32) NOT NULL, 
	run_id VARCHAR(32) NOT NULL, 
	mode VARCHAR(32) NOT NULL, 
	trace_index INTEGER NOT NULL, 
	trigger_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	decision_json JSON NOT NULL, 
	reasoning_summary TEXT NOT NULL, 
	tool_calls_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES backtest_runs (id)
);""",
    """CREATE INDEX ix_run_traces_run_id ON run_traces (run_id);""",
    """CREATE TABLE trace_execution_details (
	id VARCHAR(32) NOT NULL, 
	trace_id VARCHAR(32) NOT NULL, 
	portfolio_before_json JSON NOT NULL, 
	portfolio_after_json JSON NOT NULL, 
	fills_json JSON NOT NULL, 
	mark_prices_json JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_trace_execution_detail_trace UNIQUE (trace_id), 
	FOREIGN KEY(trace_id) REFERENCES run_traces (id)
);""",
    """CREATE INDEX ix_trace_execution_details_trace_id ON trace_execution_details (trace_id);"""
]

DOWNGRADE_STATEMENTS = [
    """DROP TABLE IF EXISTS trace_execution_details CASCADE;""",
    """DROP TABLE IF EXISTS run_traces CASCADE;""",
    """DROP TABLE IF EXISTS portfolio_positions CASCADE;""",
    """DROP TABLE IF EXISTS portfolio_fills CASCADE;""",
    """DROP TABLE IF EXISTS live_signals CASCADE;""",
    """DROP TABLE IF EXISTS strategy_states CASCADE;""",
    """DROP TABLE IF EXISTS portfolio_books CASCADE;""",
    """DROP TABLE IF EXISTS live_tasks CASCADE;""",
    """DROP TABLE IF EXISTS execution_strategy_states CASCADE;""",
    """DROP TABLE IF EXISTS backtest_runs CASCADE;""",
    """DROP TABLE IF EXISTS skills CASCADE;""",
    """DROP TABLE IF EXISTS market_sync_states CASCADE;""",
    """DROP TABLE IF EXISTS market_sync_cursors CASCADE;""",
    """DROP TABLE IF EXISTS market_sync_attempts CASCADE;""",
    """DROP TABLE IF EXISTS market_instruments CASCADE;""",
    """DROP TABLE IF EXISTS market_coverage_snapshots CASCADE;""",
    """DROP TABLE IF EXISTS market_candles CASCADE;""",
    """DROP TABLE IF EXISTS csv_ingestion_jobs CASCADE;"""
]


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
